from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from gnosia_common import ENTITY_JSON_DIRNAME, OUTPUT_DIR, ensure_dir, read_json, write_json  # noqa: E402

WORK_DIR = SCRIPT_DIR / "work"
PHASE1_ENTITIES = {
    "OthersText",
    "ScreenText",
    "ScenarioBaseText",
    "ScenarioTutorialText",
}

EXACT_TRANSLATIONS = {
    "Loop": "Loop",
    "LeVi": "LeVi",
    "???": "???",
    "Kukrushka": "Kukrushka",
    "Manan": "Manan",
    " was sent to cold sleep.": " fue a sueno frio.",
    "Takashi": "Takashi",
    "Gnosia": "Gnosia",
    "Random": "Azar",
    "Engineer": "Inge.",
    "Doctor": "Doctor",
    "Guardian Angel": "Angel guardian",
    "Guard Duty": "Guardia",
    "Crew": "Hum.",
    "AC Follower": "Seguidor AC",
    "Bug": "Bug",
    "Attack failed...": "Ataq. fallido...",
    "Nobody was attacked": "Nadie fue atacado",
    "Male": "Masc",
    "Female": "Mujer",
    "N/A": "N/A",
    "Red": "Roj",
    "Orange": "Naran.",
    "Yellow": "Amar.",
    "Light Green": "Verde claro",
    "Green": "Verde",
    "Sky Blue": "Celeste",
    "Blue": "Azul",
    "Purple": "Morado",
    "Pink": "Rosa",
    "Brown": "Marr.",
    "Black": "Negro",
    "White": "Blanc",
    "Morning": "Manana",
    "Afternoon": "Tarde",
    "Night": "Noche",
    "Charisma": "Carisma",
    "Intuition": "Intuicion",
    "Charm": "Enc.",
    "Logic": "Log.",
    "Performance": "Actuacion",
    "Stealth": "Sigilo",
    "Step Forward": "Dar un paso",
    "Definite Human": "Humano seguro",
    "Definite Enemy": "Enemigo seguro",
    "Definite Bug": "Bug seguro",
    "Say I'm Human": 'Di "humano"',
    "Vote": "Vota",
    "Don't Vote": "No votes",
    "Small Talk": "Charla",
    "Freeze All": "Todos SF",
    "Let's Collaborate": "Aliemonos",
    "Seek Agreement": "Busca apoyo",
    "Block Argument": "Bloq. arg.",
    "Exaggerate": "Exagera",
    "Obfuscate": "Ofusca",
    "Retaliate": "Replica",
    "Regret": "Queja",
    "Seek Help": "Ayuda",
    "Don't Be Fooled": "No piques",
    "Grovel": "Ruega",
    "Main Control": "Control",
    "Room": "Hab.",
    "Cafeteria": "Comedor",
    "Sleeping Area 2": "Dormit. 2",
    "Cold Sleep Chamber": "Camara SF",
    "Power Room": "Energia",
    "Sickbay": "Enferm.",
    "Viewing Lounge": "Mirador",
    "Synthesis Plant": "Sintesis",
    "dammy": "dammy",
    "Lobby": "Lobby",
    "Rec Room": "Ocio",
    "Gym": "Gim",
    "Shower Room": "Duchas",
    "Lab": "Lab",
    "Water Control Room": "Agua",
    "EVA Room": "Sala EVA",
    "Hangar": "Hangar",
    "Private Room 1": "Hab. priv. 1",
    "Private Room 3": "Hab. priv. 3",
    "Private Room 5": "Hab. priv. 5",
    "Private Room 4": "Hab. priv. 4",
    "Hall": "Hall",
    "None": "Nada",
    "Unknown": "Descon.",
    "Nothing Happened": "No paso nada",
    "Day {0} - Night": "Dia {0} - Noche",
    "Day {0}": "Dia {0}",
    "{0} has disappeared": "{0} ha desaparecido",
    "Request Reports": "Pedir informes",
    "Report": "Parte",
    "Mourn victim": "Lamentar",
    " and ": " y ",
    "Doubt": "Dudar",
    "Agree": "Apoya",
    "Defend": "Ampara",
    "Join in Defense": "Secunda",
    "Refute": "Refuta",
    "Cover": "Cubre",
    "Help cover": "Ayuda",
    "Argue": "Disc.",
    "Also Disagree": "Discrepa",
    "Express Thanks": "Agradece",
    "Shut Up": "Calla",
    "Start the Vote": "Empieza vot.",
    "Reveal Role": "Revela rol",
    "Reveal Own Role": "Revela tu rol",
    "Nobody came forward": "Nadie salio",
    "Nobody came forward...": "Nadie salio...",
    "Point Out Mistake": "Senala fallo",
    "That's wrong": "Eso no",
    "That's Obvious": "Es obvio",
    "We know that already": "Ya se sabe",
    "Recognized as Enemy": "Marcado enemigo",
    "Start the vote": "Empieza vot.",
    "The vote will now begin": "Empieza la votacion",
    "See Through Lie": "Ve la mentira",
    "human": "hum.",
    "Cold Sleep": "Sueno frio",
    "Say Goodbye": "Despidete",
    "Freeze": "Cong.",
    "Vote Again": "Revota",
    "FINAL VOTE": "VOTO FINAL",
    "The vote will be retaken": "Se repite la votacion",
    "Revote Again": "Repite vot.",
    "VOTE SUSPENDED": "VOTO PARADO",
    "Freeze Everyone": "Todos SF",
    "Freeze Nobody": "Nadie SF",
    "Agree with Plan": "Acepta plan",
    "Disagree with Plan": "Rechaza plan",
    "Draw Conclusion": "Concluye",
    "Out of Time": "Sin tiempo",
    "Please! Not cold sleep!": "Por favor, no SF",
    "React to Groveling": "Reacciona",
    "Groveling Failed": "Suplica fallida",
    "What the hell?! Jerks...": "Pero que...? Idiotas...",
    "Groveling Successful": "Suplica valida",
    "everyone": "todos",
    "Loop Creation": "Crear loop",
    "Select Destination": "Elige destino",
    "Fake Engineer": "Ing. falso",
    "Hunter": "Guarda",
    "Werewolf": "Lobo",
    "Coversation Log": "Registro",
    "Free Conversation": "Charla libre",
    "Go to Room": "Ir a hab.",
    "Select Room": "Elige hab.",
    "Say You're Human": 'Di "humano"',
    "End": "Fin",
    "Only you": "Solo tu",
    "I'm Human": "Soy hum.",
    "Stop It": "Paralo",
    "Let's not do this": "No lo hagamos",
    "Stopped": "Parado",
    "Make Small Talk": "Charla",
    "Let's talk about food": "Hablar de comida",
    "Let's talk about love": "Hablar de amor",
    "Let's tell scary stories": "Contar miedo",
    "Join In Small Talk": "Sumate charla",
    "Stop Small Talk": "Corta charla",
    "Small Talk Finished": "Fin charla",
    "Disagree": "Discrepa",
    "No, let's not do this": "No, mejor no",
    "Resist": "Resist",
    "Accept": "Acepta",
    "OK, let's work together.": "Vale, juntos.",
    "Refuse": "Niega",
    "Don't Answer": "No respondas",
    "A button": "boton A",
    "Y button": "boton Y",
    "B button": "boton B",
    "X button": "boton X",
    "L button": "boton L",
    "R button": "boton R",
    "L stick button": "stick L",
    "+ button": "boton +",
    "Create Loop": "Crear loop",
    "Scenario Preload": "Precarga",
    "Explain Situation": "Explica situac.",
    "What?! For real?!": "Como?! En serio?!",
    "No Action": "Sin act.",
    "Setsu Statement": "Setsu habla",
    "Understand?": "Entendido?",
    "Got it": "Vale",
    "I don't get it": "No lo pillo",
    "No reply": "No resp.",
    "Get up": "Arriba",
    "In the corridor": "En pasillo",
    "Yes": "Si",
    "OK... I see.": "Vale, veo.",
    "I don't think so": "No lo creo",
    "Anyway": "En fin",
    "Arrival": "Llegada",
    "Frozen": "Cong.",
    "Movement": "Moverse",
    "Oh, that's right...": "Ah, claro...",
    "Return to Room": "Volver hab.",
    "In Room": "En hab.",
    "I remember": "Recuerdo",
    '"That night"?': '"Esa noche"?',
    "Don't answer": "No respondas",
    "Keeping up?": "Sigues?",
    "I'm OK.": "Bien.",
    "I can't keep up": "No sigo",
    "Setsu conversation": "Charla Setsu",
    "After Setsu conversation": "Tras Setsu",
    "3, 2...": "3, 2...",
    "1...": "1...",
    "Morning of Day 2": "Manana dia 2",
    "Console": "Consola",
    "SQ...": "SQ...",
    "Gina annihilated.": "Gina aniquilada.",
    "After being frozen": "Tras congelar",
    "Here, take this.": "Toma esto.",
    "Hand over": "Entregar",
    "After moving": "Tras moverse",
    "See you again...": "Nos vemos...",
    "Continue": "Seguir",
    "...!": "...!",
    "To see you": "Verte",
    "To help you": "Ayudarte",
    "...": "...",
    "What's your plan?": "Cual es tu plan?",
    "Hmph, I see...": "Hm, ya veo...",
    "Listen to Setsu": "Escucha a Setsu",
    'The "Silver Key"...': 'La "Llave Plateada"...',
    "What does that mean...?": "Que significa...?",
    "Exactly.": "Exacto.",
    "Listen to Setsu ": "Escucha a Setsu",
    "Then, who...?": "Entonces...?",
    "Manan?": "Manan?",
    "Who is... Manan?": "Quien... Manan?",
    "Oh, uh, maybe.": "Eh... puede.",
    "Um... what?": "Eh... que?",
    "Think about this": "Piensalo",
    "Keep listening": "Sigue",
    "Conditions?": "Condic.?",
    "But, that means...": "Pero eso...",
    "Kukrushka?": "Kukrushka?",
    "Wait": "Alto",
    "Ah, here it is.": "Ah, aqui.",
    "A... doll?": "Una mun.?",
    "But... for what purpose?": "Pero... para que?",
    "Huh...?": "Eh...?",
    "OH-EM-GEE?!": "PERO QUE?!",
    "Hey come on...": "Venga ya...",
    "OK...": "Vale",
    "This world...?": "Este mundo...?",
    "Huh...? What...?": "Eh...? Que...?",
    "No selection": "Sin eleccion",
    "You were awesome": "Lo bordaste",
    "Really?\nGood...": "De veras?\nBien...",
    "You did well": "Bien hecho",
    "You were OK": "Bien",
    "Where is this?": "Donde es esto?",
    "Where are we...?": "Donde estamos?",
    "That's a lie!": "Mientes!",
    "Say nothing": "No hables",
    "Inside the ship": "Dentro nave",
    "What do we do?": "Que hacemos?",
    "Manual": "Manual",
    "And if we mess up?": "Y si fallamos?",
    "Attacked": "Atacado",
    "Compromise?": "Pacto?",
    "ＬｅＶｉ": "LeVi",
    "Conclusion": "Conclusion",
    "What is Gnosia?": "Que es Gnosia?",
    "Late night walk": "Paseo noct.",
    "Games": "Juego",
    "Nope.": "No.",
    "Billiards": "Billar",
    "3D Chess": "Ajed.3D",
    "What is 3D chess...?": "Que es ajed.3D...?",
    "To Cafeteria": "Al comedor",
    "Sushi": "Sushi",
    "Steak": "Carne",
    "Ramen": "Ramen",
    "To lower level": "Abajo",
    "Lower level": "Planta baja",
    "State your name": "Di tu nombre",
    "I see...": "Veo...",
    "Slept": "Durm.",
    "That's terrifying.": "Da miedo.",
    "It's OK": "Bien.",
    "I hope...": "Ojala...",
    "I'm scared, too": "Yo tambien",
    "Yes...": "Si...",
    "Listen to Gina": "Escucha a Gina",
    "After Gina CO": "Tras CO Gina",
    "Thank you...": "Gracias...",
    "Same here": "Igual",
    "Thank me more": "Dame mas",
    "Lie": "Lie",
    " is... lying.)": " miente.)",
    "CS Room": "Sala SF",
    "Um...": "Eh...",
    "Screw that...": "Paso ya...",
    "Gina... You...": "Gina... Tu...",
    "Well, yeah": "Pues si",
    "Maaan...": "Jope...",
    "Uh... did it stop?": "Eh... paro?",
    "Discovers Gnosia": "Ve Gnosia",
    "I don't know": "No lo se",
    "Let's eat": "A comer",
    "Main Console": "Consola",
    "Step forward?": "Salir?",
    "Don't step forward": "No salgas",
    "If Male": "Si masc",
    "Could you move?": "Te apartas?",
    "Ummm...": "Eeeh...",
    "Please trust me": "Confia en mi",
    "If not Male": "Si no masc.",
    "Why?": "Por?",
    "Don't worry.": "No pasa.",
    "No one was attacked.": "Nadie fue atacado.",
    "Hm?": "Hm?",
    "About Stella": "Sobre Stella",
    "Register conversation": "Registrar charla",
    "Conversation": "Conversacion",
    "Thank you": "Gracias",
    "Embrace her": "Abrazarla",
    "Explain Sitaution": "Explica situac.",
    "Where is Yuriko?": "Donde esta Yuriko?",
    "Yuriko...? Who?": "Yuriko...? Quien?",
    "Never mind": "Da igual",
    "Back to topic": "Al tema",
    "Do you like cats?": "Te gustan gatos?",
    "No": "No",
    "Comet appears": "Aparece Comet",
    "Comet night": "Noche Comet",
    "Right? OK, I trust you.": "Vale, confio.",
    "Comet continued": "Sigue Comet",
    "Be careful": "Cuidado",
    "Liar": "Mnt.",
    "Hey, this'll be easy!": "Esto sera facil!",
    "Raqio CO": "CO Raqio",
    "Room night": "Noche hab.",
    "10, 9, 8, 7, 6, 5, 4...": "10, 9, 8, 7, 6, 5, 4...",
    "Hmph.": "Hm.",
    "Yeah, so?": "Si, y?",
    "I don't understand": "No entiendo",
    "I see": "Veo",
    "To select screen": "A seleccion",
    "Selection OK": "Seleccion OK",
    "Win": "Gan",
    "I tried hard, too": "Yo tambien.",
    "Impossible.": "Imposible.",
    "Oh...": "Oh...",
    "Listen to Stella": "Escucha a Stella",
    "AC Follower?": "Seguidor AC?",
    "Move": "Ve",
    "Register Conversation": "Registrar charla",
    "Ooh...": "Oh...",
    "Listen": "Oye",
    "After Jonas CO": "Tras CO Jonas",
    "Key?": "Key?",
    "How?": "Como",
    "About loops": "Sobre loops",
    "Search together": "Buscar juntos",
    "I'm Gnosia.": "Soy Gnosia.",
    "Free talk": "Charla",
    "Ending": "Final",
    "With Setsu": "Con Setsu",
    "Why...?": "Por...?",
    "Not on purpose": "Sin querer",
    "I forgot": "Olvide",
    "OK": "OK",
    "After Loop creation": "Tras crear loop",
    "Night Shamin": "Noche Shamin",
    "You replied OK.": "Respondiste OK.",
    "To recreation room": "A sala ocio",
    "Don't state name": "No lo digas",
    "After introduction": "Tras presentarse",
    "Shamin appears": "Aparece Shamin",
    "It's Yuriko...": "Es Yuriko...",
    "I understand...": "Entiendo...",
    "Listen to Yuriko": "Escucha a Yuriko",
    "Continue talk": "Seguir charla",
    "Otome night": "Noche Otome",
    "Can I... help you?": "Puedo... ayudarte?",
    "Spilt water": "Derrame",
    "What's going on?": "Que pasa?",
    "Continue conversation": "Seguir charla",
    "Compliment him": "Elogiarlo",
    "Teach me about it": "Ensenamelo",
    "Night noises": "Ruidos noche",
    "Bug End": "Fin Bug",
    "Setsu night": "Noche Setsu",
    "Please tell me": "Dimelo",
    "No need": "No hace",
    "Don't respond": "No respondas",
    "About Engineers": "Sobre ingenieros",
    "Experiment": "Prueba",
    "After CO": "Tras CO",
    "Forcing termination now.": "Forzando cierre.",
    "Failed to save data.": "Error al guardar.",
    "Please select a save slot.": "Elige una ranura.",
    "Unable to create save slot.": "No se pudo crear.",
    "Unable to delete save slot.": "No se pudo borrar.",
    "Notes": "Notas",
    "Day ": "Dia ",
    " - Revote": " - Revoto",
    " - Revote ": " - Revoto ",
    "Change Page            ": "Cambiar pag.         ",
    "Select　　Back　　Recall": "Elegir  Atras  Ver ",
    "Move Up/Down         ": "Subir/Bajar       ",
    "Zoom In/Out         ": "Zoom +/-         ",
    "Move Left/Right         ": "Izq./Der.         ",
    "Alt. Image         ": "Imagen alt.       ",
    "Move Up/Down             ": "Subir/Bajar           ",
    "Zoom In/Out             ": "Zoom +/-             ",
    "Move Left/Right             ": "Izq./Der.             ",
    "Alt. Image             ": "Imagen alt.           ",
    "Basic Rules": "Reglas base",
    "Screen Explanation": "Sobre pantallas",
    "Advancing the Story": "Avanzar trama",
    "Q&A  (Part 1) ": "P y R (1)    ",
    "Q&A  (Part 2) ": "P y R (2)    ",
    "Game Overview": "Resumen",
    "List of Roles": "Lista roles",
    "Discussion  (Likeability/Trust) ": "Debate (afin/conf.)            ",
    "Discussion  (Hate) ": "Debate (odio)    ",
    "Abilities (Charm/Stealth) ": "Apt. (enc./sig.)      ",
    "Abilities (Intuition) ": "Apt. (intuicion) ",
    "Skills": "Tecs.",
    "Nighttime Movement Part": "Moverse de noche",
    "Logical Inconsistency (1)": "Fallo logico (1)",
    "Logical Inconsistency (2)": "Fallo logico (2)",
    "Logical Inconsistency (3)": "Fallo logico (3)",
    "Normal Screen": "Pantalla base",
    "Current Status ": "Estado actual ",
    "Current Settings ": "Ajustes act. ",
    "Data Reference": "Datos ref.",
    "Log": "Log",
    "Crew Member Data": "Datos tripul.",
    "Engineer Report": "Informe ing.",
    "Doctor Report": "Informe doct.",
    "Start Menu": "Inicio",
    "Movement Screen (Night Part)": "Pant. mov. noche",
    "Results": "Resul.",
    "Setup": "Cfg.",
    "Unlock Notes": "Notas extra",
    "Event Search": "Busca ev.",
    "Foster Relationships": "Crear lazos",
    'I\'m told I\'m "Annoying"...': 'Me dicen "pesado"...',
    "The Gnosia Got me again...": "Gnosia me dio otra vez...",
    "Why does everyone hate me?": "Por que me odian?",
    "Nobody listens to me": "Nadie me escucha",
    "What is Definite Enemy (Human)?": "Que es enemigo/humano seguro?",
    "I have no idea what to do now...": "No se que hacer ahora...",
    "Keyboard configuration layout": "Esquema teclado",
    "Controller configuration layout": "Esquema mando",
    "Autosave": "Auto",
    "Before Gnosia Attack": "Antes ataque",
    "After Gnosia Attack": "Tras ataque",
    "Failed to load data.": "Error al cargar.",
    "Join Defense": "Secunda",
    "Cover Together": "Cubrid",
    "Say Thanks": "Da gracias",
    "Join Argument": "Secunda",
    " YES           NO": " SI            NO",
    "Begin from beginning of loop?": "Empezar loop?",
    "Your Role": "Tu rol",
    "Are these conditions OK?": "Asi esta bien?",
    'Your role is now "': 'Tu rol ahora es "',
    '".': '".',
    "\n": "\n",
    ", ": ", ",
    " will become a friend.": " sera amigo.",
    'New Skill: "': 'Nueva tecn.: "',
    '"\ncan now be used.': '"\nya se puede usar.',
    "You have been... annihilated.": "Has sido... aniquilado.",
    "Dead\n": "Muerto\n",
    "Frozen\n": "Cong.\n",
    "Lost\n": "Perd.\n",
    "The Gnosia are... no more.": "Gnosia... ya no esta.",
    "Won\n": "Gana\n",
    "End\n": "Fin\n",
    "EXP Up": "EXP +",
    "Lv. Up Possible": "Sube nivel",
    "Human\nGnosia": "Humano\nGnosia",
    "Is this OK?": "Esta bien?",
    "Failed to load system data.": "Error datos sist.",
    "Ad astra per aspera.": "Ad astra per aspera.",
    "Last night, ": "Anoche, ",
    " disappeared.": " desaparecio.",
    "No one was attacked last night.": "Anoche no atacaron a nadie.",
    "Investigation revealed that ": "La investigacion vio que ",
    " was Gnosia": " era Gnosia",
    ".": ".",
    " was human.": " era hum.",
    "\nwas Gnosia.": "\nera Gnosia.",
}


CONTEXT_TRANSLATIONS = {
    ("OthersText", "MessageLog", "(It's... no use. I can't remember anymore.)"): "(Ya... no sirve. No recuerdo mas.)",
    ("OthersText", "MessageLog", "(Up to here, it's empty...)"): "(Hasta aqui, vacio...)",
    ("OthersText", "MessageLog", "(That's all I remember clearly.)"): "(Eso es lo ultimo que recuerdo bien.)",
    ("OthersText", "MessageLog", "(I don't remember anything before this.)"): "(No recuerdo nada anterior.)",
    ("OthersText", "MessageLog", "(That's as far as I can remember...)"): "(Hasta ahi llega mi recuerdo...)",
    ("OthersText", "MessageLog", "(My memory suddenly cuts off.)"): "(Mi memoria se corta aqui.)",
    ("OthersText", "MessageLog", "(Looks like this is the extent of my memory.)"): "(Parece que hasta ahi llega mi memoria.)",
    ("OthersText", "MessageLog", "(My memories begin here.)"): "(Mis recuerdos empiezan aqui.)",
    ("OthersText", "MessageLog", "(Anything prior to this is likely inaccurate.)"): "(Lo anterior seguramente sea inexacto.)",
    ("OthersText", "MessageLog", "(The continuity of myself seems to break off here.)"): "(Mi continuidad parece romperse aqui.)",
    ("ScreenText", "title_load_screen", "Ad astra per aspera."): "Ad astra per aspera.",
    ("ScenarioBaseText", "Talk", "Free Conversation Preparation"): "Prep. charla libre",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply the first manual ES-over-EN translation batch.")
    parser.add_argument(
        "--source-manifest",
        type=Path,
        default=OUTPUT_DIR / "manifest.json",
        help="Snapshot manifest with the original English slot.",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=WORK_DIR,
        help="Tracked work corpus directory.",
    )
    parser.add_argument(
        "--force-init",
        action="store_true",
        help="Recreate the work directory from the source snapshot before applying translations.",
    )
    return parser.parse_args()


def initialize_work(source_manifest: Path, work_dir: Path, force: bool) -> None:
    if work_dir.exists() and not force:
        return

    if work_dir.exists():
        shutil.rmtree(work_dir)

    manifest = read_json(source_manifest)
    source_base = source_manifest.parent
    ensure_dir(work_dir / ENTITY_JSON_DIRNAME)
    for entry in manifest["entities"]:
        src = source_base / entry["file"]
        dst = work_dir / entry["file"]
        ensure_dir(dst.parent)
        shutil.copy2(src, dst)

    manifest = dict(manifest)
    manifest["translation_target_language"] = "es"
    manifest["translation_overrides_slot"] = "en"
    manifest["translation_source_manifest"] = str(source_manifest.resolve())
    write_json(work_dir / "manifest.json", manifest)


def translate_text(entity_name: str, sheet_name: str, source_text: str) -> str:
    context_key = (entity_name, sheet_name, source_text)
    if context_key in CONTEXT_TRANSLATIONS:
        return CONTEXT_TRANSLATIONS[context_key]
    return EXACT_TRANSLATIONS.get(source_text, source_text)


def main() -> int:
    args = parse_args()
    initialize_work(args.source_manifest, args.work_dir, args.force_init)
    manifest = read_json(args.work_dir / "manifest.json")

    changed = 0
    touched_entities = 0
    for entry in manifest["entities"]:
        entity_path = args.work_dir / entry["file"]
        payload = read_json(entity_path)
        entity_name = payload["entity_name"]
        if entity_name not in PHASE1_ENTITIES:
            continue

        entity_changed = False
        for sheet in payload["sheets"]:
            sheet_name = sheet["name"]
            for param in sheet["params"]:
                texts = param["texts"]
                if len(texts) < 2:
                    continue
                source_text = texts[1]
                translated = translate_text(entity_name, sheet_name, source_text)
                if translated != source_text:
                    texts[1] = translated
                    changed += 1
                    entity_changed = True

        if entity_changed:
            write_json(entity_path, payload)
            touched_entities += 1

    print(f"Manual phase-1 batch applied: {changed} strings updated across {touched_entities} entities.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
